name: CI-macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2.1.1
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install from source
        run: |
          pip install --upgrade pip setuptools wheel
          pip install .[all]

      - name: Tests
        run: pytest --cov=h3 --full-trace
