name: CI-windows-py27

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CC: cl.exe
  CXX: cl.exe

jobs:
  tests:
    name: Python 2.7
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.1.1
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.0
        # with:
        #   vs-version: [16.4, 16.5]

      - uses: ilammy/msvc-dev-cmd@v1.2.0
        with:
          toolset: 9.0

      - name: Install dependencies
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel

      - name: install from source
        run: pip install .

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Lint
        run: flake8 src/h3 setup.py tests

      - name: Tests
        run: pytest --cov=h3 --full-trace --cov-report=xml
