name: wheels-linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    name: Python Wheels Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.1
        with:
          submodules: recursive

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build wheels
        env:
          CIBW_SKIP: pp* cp27* *-manylinux_i686
          CIBW_TEST_REQUIRES: pytest numpy
          CIBW_TEST_COMMAND: pytest {project}/tests
        run: |
          pip install --upgrade cibuildwheel pip setuptools wheel
          python -m cibuildwheel --output-dir wheelhouse

      - name: Build sdist
        run: |
          pip install scikit-build
          python setup.py sdist --dist-dir=wheelhouse

      # - name: Upload artifacts to github
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: wheels
      #     path: ./wheelhouse
